# NUMPY

1. [NEDEN NUMPY?](#neden-numpy)
2. [NUMPY ARRAY](#numpy-array)
    1. [Liste ile array oluşturma](#liste-ile-array-oluşturma)
    2. [Sıfırdan array oluşturma](#sıfırdan-array-oluşturma)
    3. [Array özellikleri](#array-özellikleri)
    4. [Reshaping (Yeniden Şekillendirmek)](#reshaping-yeniden-şekillendirmek)
    5. [Concantenation (Birleştirme)](#concantenation-birleştirme)
    6. [Splitting (Ayırma)](#splitting-ayırma)
    7. [Sorting (Sıralama)](#sorting-sıralama)
    8. [İndeks ile Elemanlara Erişmek](#i̇ndeks-ile-elemanlara-erişmek)
    9. [Slicing (Array Alt Küme İşlemleri)](#slicing-array-alt-küme-i̇şlemleri)
    10. [Alt Küme Üzerinde İşlem Yapmak](#alt-küme-üzerinde-i̇şlem-yapmak)

## NEDEN NUMPY?

In [225]:
a = [1,2,3,4]
b = [2,3,4,5]

In [226]:
ab = []
for i in range (0,len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [227]:
import numpy as np

In [228]:
c = np.array([1,2,3,4]) 
d = np.array([2,3,4,5])

In [229]:
c * d

array([ 2,  6, 12, 20])

## NUMPY ARRAY

### Liste ile array oluşturma

In [230]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [231]:
a = np.array([1,2,3,4,5])

In [232]:
type(a)

numpy.ndarray

In [233]:
np.array([3.14,2,10,20], dtype = ("float32"))

array([ 3.14,  2.  , 10.  , 20.  ], dtype=float32)

In [234]:
np.array([3.14,2,10,20], dtype = ("int"))

array([ 3,  2, 10, 20])

### Sıfırdan array oluşturma

In [235]:
np.zeros(10 , dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [236]:
np.ones((3,5),dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [237]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [238]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [239]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [240]:
np.random.normal(10, 4, (3,4))

array([[11.69577228,  8.23293591,  9.66333966, 14.94806429],
       [ 4.29408446, 11.35209064, 17.89828479, 17.86013906],
       [ 2.24035513,  6.94949214, 10.67463755,  4.7124922 ]])

In [241]:
np.random.randint(0, 10, (3,3))

array([[5, 7, 4],
       [3, 1, 5],
       [5, 0, 8]])

### Array Özellikleri 

* **ndim** : _boyut sayısı_
* **shape** : _boyut bilgisi_
* **size** : _toplam eleman sayısı_
* **dtype** : _array veri tipi_

In [242]:
np.random.randint(10, size=10)

array([5, 2, 3, 3, 2, 9, 2, 2, 3, 6])

In [243]:
e = np.random.randint(10, size=10)

In [244]:
e.ndim

1

In [245]:
e.shape

(10,)

In [246]:
e.size

10

In [247]:
e.dtype

dtype('int32')

In [248]:
f = np.random.randint(10, size= (3,5))
f

array([[1, 6, 9, 2, 6],
       [9, 8, 3, 0, 1],
       [0, 4, 4, 6, 8]])

In [249]:
f.ndim

2

In [250]:
f.shape

(3, 5)

In [251]:
f.size

15

In [252]:
f.dtype

dtype('int32')

### Reshaping (Yeniden Şekillendirmek)

In [253]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [254]:
np.arange(1, 10, 1).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [255]:
g = np.arange(1, 10, 1)
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [256]:
g.ndim

1

In [257]:
h = g.reshape((1,9))
h

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [258]:
h.ndim

2

### Concantenation (Birleştirme)

In [259]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [260]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [261]:
z = np.array([7,8,9])

In [262]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [263]:
# 2 boyut için concatenate

In [264]:
a = np.array([[1,2,3], [4,5,6]])

In [265]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [266]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Splitting (Ayırma)


In [267]:
x = np.array([1,2,3,99,99,3,2,1])

In [268]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [269]:
a,b,c = np.split(x, [3,5])

In [270]:
print(a,b,c)

[1 2 3] [99 99] [3 2 1]


In [271]:
# 2 boyutlu split

In [272]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [273]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [274]:
ust, alt = np.vsplit(m, [2])

In [275]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [276]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [277]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [278]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [279]:
sag, sol = np.hsplit(m, [2])

In [280]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [281]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Sorting (Sıralama)

In [282]:
v = np.array([2,1,4,3,5])

In [283]:
v

array([2, 1, 4, 3, 5])

In [284]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [285]:
v

array([2, 1, 4, 3, 5])

In [286]:
v.sort()

In [287]:
v

array([1, 2, 3, 4, 5])

In [288]:
# 2 boyutlu sort

In [289]:
m = np.random.normal(20,5, (3,3))

In [290]:
m

array([[16.6587665 , 24.82405291, 14.67584424],
       [20.543559  , 20.52881824, 24.60333358],
       [18.86638772, 23.26524156, 25.51343733]])

In [291]:
np.sort(m, axis = 1) # her bir satırı sıralar 

array([[14.67584424, 16.6587665 , 24.82405291],
       [20.52881824, 20.543559  , 24.60333358],
       [18.86638772, 23.26524156, 25.51343733]])

In [292]:
np.sort(m, axis = 0) # her bir sütunu sıralar

array([[16.6587665 , 20.52881824, 14.67584424],
       [18.86638772, 23.26524156, 24.60333358],
       [20.543559  , 24.82405291, 25.51343733]])

### İndeks ile Elemanlara Erişmek

In [293]:
a = np.random.randint(10, size = 10)
a

array([2, 8, 2, 8, 1, 1, 1, 5, 2, 8])

In [294]:
a[0]

2

In [295]:
a[-1]

8

In [296]:
a[0] = 100

In [297]:
a

array([100,   8,   2,   8,   1,   1,   1,   5,   2,   8])

In [298]:
m = np.random.randint(10, size = (3,5))
m

array([[3, 0, 3, 0, 4],
       [3, 7, 7, 6, 2],
       [0, 0, 2, 5, 6]])

In [299]:
m[0,0]

3

In [300]:
m[1,1]

7

In [301]:
m[1,4]

2

In [302]:
m[1,4] = 99

In [303]:
m

array([[ 3,  0,  3,  0,  4],
       [ 3,  7,  7,  6, 99],
       [ 0,  0,  2,  5,  6]])

In [304]:
m[1,4] = 2.2

In [305]:
m

array([[3, 0, 3, 0, 4],
       [3, 7, 7, 6, 2],
       [0, 0, 2, 5, 6]])

### Slicing (Array Alt Küme İşlemleri)

In [306]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [307]:
a[0:3] # 0,1,2 indexlerini getirir

array([20, 21, 22])

In [308]:
a[:3] # baştan 3. indexe kadar

array([20, 21, 22])

In [309]:
a[3:] # 3. indexten sona kadar

array([23, 24, 25, 26, 27, 28, 29])

In [310]:
a[1::2] #1 den başla 2 şer 2 şer git

array([21, 23, 25, 27, 29])

In [311]:
a[0::2] # 2 şer 2 şer git

array([20, 22, 24, 26, 28])

In [312]:
a[0::3] # 3 er 3 er git

array([20, 23, 26, 29])

In [313]:
# 2 boyutlu slice işlemleri

In [314]:
m = np.random.randint(10, size = (5,5))

In [315]:
m

array([[5, 5, 5, 2, 5],
       [7, 1, 4, 0, 0],
       [4, 2, 3, 2, 0],
       [0, 4, 5, 2, 8],
       [4, 7, 0, 4, 2]])

In [316]:
m[:,0] # tüm satırların 0. sütununu getir

array([5, 7, 4, 0, 4])

In [317]:
m[:,1] # tüm satırların 1. sütununu getir

array([5, 1, 2, 4, 7])

In [318]:
m[:,4] # tüm satırların 4. sütununu getir

array([5, 0, 0, 8, 2])

In [319]:
m[0,:] # 0. satırın tüm sütunlarını getir

array([5, 5, 5, 2, 5])

In [320]:
m[0] # 0. satırın tüm sütunlarını getir

array([5, 5, 5, 2, 5])

In [321]:
m[1,:] # 1. satırın tüm sütunlarını getir

array([7, 1, 4, 0, 0])

In [322]:
m[1] # 1. satırın tüm sütunlarını getir

array([7, 1, 4, 0, 0])

In [323]:
m[0:2,0:3] # 0. ve 1. satırların 0,1,2. sütunlarını getir

array([[5, 5, 5],
       [7, 1, 4]])

In [324]:
m[::,:2] # tüm satırların 0 ve 1. sütunlarını getir

array([[5, 5],
       [7, 1],
       [4, 2],
       [0, 4],
       [4, 7]])

In [325]:
m[:,0:2] # tüm satırların 0 ve 1. sütunlarını getir

array([[5, 5],
       [7, 1],
       [4, 2],
       [0, 4],
       [4, 7]])

In [326]:
m

array([[5, 5, 5, 2, 5],
       [7, 1, 4, 0, 0],
       [4, 2, 3, 2, 0],
       [0, 4, 5, 2, 8],
       [4, 7, 0, 4, 2]])

In [327]:
m[1:3,0:2] # 1 ve 2. satırların 0 ve 1. sütunlarını getir

array([[7, 1],
       [4, 2]])

### Alt Küme Üzerinde İşlem Yapmak