# NUMPY

1. [NEDEN NUMPY?](#neden-numpy)
2. [NUMPY ARRAY](#numpy-array)
    1. [Liste ile array oluşturma](#liste-ile-array-oluşturma)
    2. [Sıfırdan array oluşturma](#sıfırdan-array-oluşturma)
    3. [Array özellikleri](#array-özellikleri)
    4. [Reshaping (Yeniden Şekillendirmek)](#reshaping-yeniden-şekillendirmek)
    5. [Concantenation (Birleştirme)](#concantenation-birleştirme)
    6. [Splitting (Ayırma)](#splitting-ayırma)
    7. [Sorting (Sıralama)](#sorting-sıralama)
    8. [İndeks ile Elemanlara Erişmek](#i̇ndeks-ile-elemanlara-erişmek)
    9. [Slicing (Array Alt Küme İşlemleri)](#slicing-array-alt-küme-i̇şlemleri)
    10. [Alt Küme Üzerinde İşlem Yapmak](#alt-küme-üzerinde-i̇şlem-yapmak)

## NEDEN NUMPY?

In [328]:
a = [1,2,3,4]
b = [2,3,4,5]

In [329]:
ab = []
for i in range (0,len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [330]:
import numpy as np

In [331]:
c = np.array([1,2,3,4]) 
d = np.array([2,3,4,5])

In [332]:
c * d

array([ 2,  6, 12, 20])

## NUMPY ARRAY

### Liste ile array oluşturma

In [333]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [334]:
a = np.array([1,2,3,4,5])

In [335]:
type(a)

numpy.ndarray

In [336]:
np.array([3.14,2,10,20], dtype = ("float32"))

array([ 3.14,  2.  , 10.  , 20.  ], dtype=float32)

In [337]:
np.array([3.14,2,10,20], dtype = ("int"))

array([ 3,  2, 10, 20])

### Sıfırdan array oluşturma

In [338]:
np.zeros(10 , dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [339]:
np.ones((3,5),dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [340]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [341]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [342]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [343]:
np.random.normal(10, 4, (3,4))

array([[ 6.20192382,  7.61241067,  9.555184  ,  3.00372226],
       [ 4.63438601,  3.51322152,  5.40912011, 15.55841131],
       [ 6.57903792,  5.89175296, 13.53135064,  8.20278246]])

In [344]:
np.random.randint(0, 10, (3,3))

array([[8, 5, 6],
       [9, 6, 9],
       [2, 1, 8]])

### Array Özellikleri 

* **ndim** : _boyut sayısı_
* **shape** : _boyut bilgisi_
* **size** : _toplam eleman sayısı_
* **dtype** : _array veri tipi_

In [345]:
np.random.randint(10, size=10)

array([7, 9, 6, 8, 3, 3, 0, 7, 2, 6])

In [346]:
e = np.random.randint(10, size=10)

In [347]:
e.ndim

1

In [348]:
e.shape

(10,)

In [349]:
e.size

10

In [350]:
e.dtype

dtype('int32')

In [351]:
f = np.random.randint(10, size= (3,5))
f

array([[5, 0, 3, 9, 5],
       [5, 4, 0, 7, 4],
       [4, 6, 3, 5, 3]])

In [352]:
f.ndim

2

In [353]:
f.shape

(3, 5)

In [354]:
f.size

15

In [355]:
f.dtype

dtype('int32')

### Reshaping (Yeniden Şekillendirmek)

In [356]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [357]:
np.arange(1, 10, 1).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [358]:
g = np.arange(1, 10, 1)
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [359]:
g.ndim

1

In [360]:
h = g.reshape((1,9))
h

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [361]:
h.ndim

2

### Concantenation (Birleştirme)

In [362]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [363]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [364]:
z = np.array([7,8,9])

In [365]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [366]:
# 2 boyut için concatenate

In [367]:
a = np.array([[1,2,3], [4,5,6]])

In [368]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [369]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Splitting (Ayırma)


In [370]:
x = np.array([1,2,3,99,99,3,2,1])

In [371]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [372]:
a,b,c = np.split(x, [3,5])

In [373]:
print(a,b,c)

[1 2 3] [99 99] [3 2 1]


In [374]:
# 2 boyutlu split

In [375]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [376]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [377]:
ust, alt = np.vsplit(m, [2])

In [378]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [379]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [380]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [381]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [382]:
sag, sol = np.hsplit(m, [2])

In [383]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [384]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Sorting (Sıralama)

In [385]:
v = np.array([2,1,4,3,5])

In [386]:
v

array([2, 1, 4, 3, 5])

In [387]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [388]:
v

array([2, 1, 4, 3, 5])

In [389]:
v.sort()

In [390]:
v

array([1, 2, 3, 4, 5])

In [391]:
# 2 boyutlu sort

In [392]:
m = np.random.normal(20,5, (3,3))

In [393]:
m

array([[28.31884895, 16.30381784, 19.46402762],
       [17.56891357, 27.96490897, 17.830292  ],
       [16.33653899, 17.10861543, 19.32141309]])

In [394]:
np.sort(m, axis = 1) # her bir satırı sıralar 

array([[16.30381784, 19.46402762, 28.31884895],
       [17.56891357, 17.830292  , 27.96490897],
       [16.33653899, 17.10861543, 19.32141309]])

In [395]:
np.sort(m, axis = 0) # her bir sütunu sıralar

array([[16.33653899, 16.30381784, 17.830292  ],
       [17.56891357, 17.10861543, 19.32141309],
       [28.31884895, 27.96490897, 19.46402762]])

### İndeks ile Elemanlara Erişmek

In [396]:
a = np.random.randint(10, size = 10)
a

array([4, 0, 9, 9, 0, 1, 5, 8, 7, 4])

In [397]:
a[0]

4

In [398]:
a[-1]

4

In [399]:
a[0] = 100

In [400]:
a

array([100,   0,   9,   9,   0,   1,   5,   8,   7,   4])

In [401]:
m = np.random.randint(10, size = (3,5))
m

array([[0, 6, 4, 5, 6],
       [2, 9, 2, 4, 5],
       [8, 4, 0, 3, 4]])

In [402]:
m[0,0]

0

In [403]:
m[1,1]

9

In [404]:
m[1,4]

5

In [405]:
m[1,4] = 99

In [406]:
m

array([[ 0,  6,  4,  5,  6],
       [ 2,  9,  2,  4, 99],
       [ 8,  4,  0,  3,  4]])

In [407]:
m[1,4] = 2.2

In [408]:
m

array([[0, 6, 4, 5, 6],
       [2, 9, 2, 4, 2],
       [8, 4, 0, 3, 4]])

### Slicing (Array Alt Küme İşlemleri)

In [409]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [410]:
a[0:3] # 0,1,2 indexlerini getirir

array([20, 21, 22])

In [411]:
a[:3] # baştan 3. indexe kadar

array([20, 21, 22])

In [412]:
a[3:] # 3. indexten sona kadar

array([23, 24, 25, 26, 27, 28, 29])

In [413]:
a[1::2] #1 den başla 2 şer 2 şer git

array([21, 23, 25, 27, 29])

In [414]:
a[0::2] # 2 şer 2 şer git

array([20, 22, 24, 26, 28])

In [415]:
a[0::3] # 3 er 3 er git

array([20, 23, 26, 29])

In [416]:
# 2 boyutlu slice işlemleri

In [417]:
m = np.random.randint(10, size = (5,5))

In [418]:
m

array([[9, 9, 4, 6, 3],
       [0, 4, 6, 9, 9],
       [5, 4, 3, 1, 3],
       [9, 9, 2, 9, 0],
       [7, 4, 3, 7, 6]])

In [419]:
m[:,0] # tüm satırların 0. sütununu getir

array([9, 0, 5, 9, 7])

In [420]:
m[:,1] # tüm satırların 1. sütununu getir

array([9, 4, 4, 9, 4])

In [421]:
m[:,4] # tüm satırların 4. sütununu getir

array([3, 9, 3, 0, 6])

In [422]:
m[0,:] # 0. satırın tüm sütunlarını getir

array([9, 9, 4, 6, 3])

In [423]:
m[0] # 0. satırın tüm sütunlarını getir

array([9, 9, 4, 6, 3])

In [424]:
m[1,:] # 1. satırın tüm sütunlarını getir

array([0, 4, 6, 9, 9])

In [425]:
m[1] # 1. satırın tüm sütunlarını getir

array([0, 4, 6, 9, 9])

In [426]:
m[0:2,0:3] # 0. ve 1. satırların 0,1,2. sütunlarını getir

array([[9, 9, 4],
       [0, 4, 6]])

In [427]:
m[::,:2] # tüm satırların 0 ve 1. sütunlarını getir

array([[9, 9],
       [0, 4],
       [5, 4],
       [9, 9],
       [7, 4]])

In [428]:
m[:,0:2] # tüm satırların 0 ve 1. sütunlarını getir

array([[9, 9],
       [0, 4],
       [5, 4],
       [9, 9],
       [7, 4]])

In [429]:
m

array([[9, 9, 4, 6, 3],
       [0, 4, 6, 9, 9],
       [5, 4, 3, 1, 3],
       [9, 9, 2, 9, 0],
       [7, 4, 3, 7, 6]])

In [430]:
m[1:3,0:2] # 1 ve 2. satırların 0 ve 1. sütunlarını getir

array([[0, 4],
       [5, 4]])

### Alt Küme Üzerinde İşlem Yapmak