# NUMPY

## NEDEN NUMPY? 

In [45]:
a = [1,2,3,4]
b = [2,3,4,5]

In [46]:
ab = []
for i in range (0,len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [47]:
import numpy as np

In [48]:
c = np.array([1,2,3,4]) 
d = np.array([2,3,4,5])

In [49]:
c * d

array([ 2,  6, 12, 20])

## NUMPY ARRAY

### Liste ile array oluşturma

In [50]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [51]:
a = np.array([1,2,3,4,5])

In [52]:
type(a)

numpy.ndarray

In [53]:
np.array([3.14,2,10,20], dtype = ("float32"))

array([ 3.14,  2.  , 10.  , 20.  ], dtype=float32)

In [54]:
np.array([3.14,2,10,20], dtype = ("int"))

array([ 3,  2, 10, 20])

### Sıfırdan array oluşturma

In [55]:
np.zeros(10 , dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
np.ones((3,5),dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [58]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [59]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [60]:
np.random.normal(10, 4, (3,4))

array([[11.99710372, 11.05648395,  8.42019652,  6.82473518],
       [11.9183905 , 13.96154767,  8.27058022,  9.33163989],
       [10.21216562, 15.20420632, 13.55530468,  8.67408555]])

In [61]:
np.random.randint(0, 10, (3,3))

array([[7, 4, 1],
       [6, 3, 1],
       [5, 5, 2]])

### Array Özellikleri 

* **ndim** : _boyut sayısı_
* **shape** : _boyut bilgisi_
* **size** : _toplam eleman sayısı_
* **dtype** : _array veri tipi_

In [62]:
np.random.randint(10, size=10)

array([8, 2, 7, 7, 0, 6, 5, 4, 4, 1])

In [63]:
e = np.random.randint(10, size=10)

In [64]:
e.ndim

1

In [65]:
e.shape

(10,)

In [66]:
e.size

10

In [67]:
e.dtype

dtype('int32')

In [68]:
f = np.random.randint(10, size= (3,5))
f

array([[6, 8, 3, 5, 8],
       [4, 5, 4, 9, 4],
       [5, 4, 6, 3, 9]])

In [69]:
f.ndim

2

In [70]:
f.shape

(3, 5)

In [71]:
f.size

15

In [72]:
f.dtype

dtype('int32')

### Reshaping (Yeniden Şekillendirmek)

In [73]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.arange(1, 10, 1).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
g = np.arange(1, 10, 1)
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
g.ndim

1

In [79]:
h = g.reshape((1,9))
h

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [80]:
h.ndim

2