# NUMPY

## NEDEN NUMPY? 

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

In [3]:
ab = []
for i in range (0,len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [4]:
import numpy as np

In [5]:
c = np.array([1,2,3,4]) 
d = np.array([2,3,4,5])

In [6]:
c * d

array([ 2,  6, 12, 20])

## NUMPY ARRAY

### Liste ile array oluşturma

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
a = np.array([1,2,3,4,5])

In [9]:
type(a)

numpy.ndarray

In [10]:
np.array([3.14,2,10,20], dtype = ("float32"))

array([ 3.14,  2.  , 10.  , 20.  ], dtype=float32)

In [11]:
np.array([3.14,2,10,20], dtype = ("int"))

array([ 3,  2, 10, 20])

### Sıfırdan array oluşturma

In [12]:
np.zeros(10 , dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5),dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [15]:
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10, 4, (3,4))

array([[13.64317819, 14.24127344,  8.76381554, 12.29064535],
       [ 8.71622522, 12.35711178, 16.40694325,  5.97230661],
       [12.14544585,  8.59999456,  4.19208992, 10.94668867]])

In [18]:
np.random.randint(0, 10, (3,3))

array([[6, 9, 0],
       [7, 9, 3],
       [2, 7, 9]])

### Array Özellikleri 

* **ndim** : _boyut sayısı_
* **shape** : _boyut bilgisi_
* **size** : _toplam eleman sayısı_
* **dtype** : _array veri tipi_

In [19]:
np.random.randint(10, size=10)

array([8, 1, 6, 5, 8, 1, 3, 7, 3, 6])

In [20]:
e = np.random.randint(10, size=10)

In [21]:
e.ndim

1

In [22]:
e.shape

(10,)

In [23]:
e.size

10

In [24]:
e.dtype

dtype('int32')

In [25]:
f = np.random.randint(10, size= (3,5))
f

array([[3, 2, 6, 9, 7],
       [0, 7, 1, 3, 9],
       [8, 3, 4, 5, 1]])

In [26]:
f.ndim

2

In [27]:
f.shape

(3, 5)

In [28]:
f.size

15

In [29]:
f.dtype

dtype('int32')

### Reshaping (Yeniden Şekillendirmek)

In [30]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(1, 10, 1).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
g = np.arange(1, 10, 1)
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
g.ndim

1

In [34]:
h = g.reshape((1,9))
h

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
h.ndim

2